# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXXQicka0Z6lX4O8NS4-FrmTjzyT6Yse
"""

name = input("What is your name? ")
print("Hello,", name)

